const CHARACTER_SPRITES = {
  IDLE_ANIMATION: [
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_000.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_001.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_002.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_003.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_004.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_005.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_006.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_007.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_008.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_009.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_010.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_011.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_012.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_013.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_014.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_015.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_016.png',
    './img/Character/lvl_1/Idle/0_Dark_Oracle_Idle_017.png',
  ],
  WALKING_ANIMATION: [
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_000.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_001.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_002.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_003.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_004.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_005.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_006.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_007.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_008.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_009.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_010.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_011.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_012.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_013.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_014.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_015.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_016.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_017.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_018.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_019.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_020.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_021.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_022.png',
    './img/Character/lvl_1/Walking/0_Dark_Oracle_Walking_023.png',
  ],
  RUNNING_ANIMATION: [
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_000.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_001.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_002.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_003.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_004.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_005.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_006.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_007.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_008.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_009.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_010.png',
    './img/Character/lvl_1/Running/0_Dark_Oracle_Running_011.png',
  ],
  JUMPING_ANIMATION: [
    './img/Character/lvl_1/Jump Start/0_Dark_Oracle_Jump Start_000.png',
    './img/Character/lvl_1/Jump Start/0_Dark_Oracle_Jump Start_001.png',
    './img/Character/lvl_1/Jump Start/0_Dark_Oracle_Jump Start_002.png',
    './img/Character/lvl_1/Jump Start/0_Dark_Oracle_Jump Start_003.png',
    './img/Character/lvl_1/Jump Start/0_Dark_Oracle_Jump Start_004.png',
    './img/Character/lvl_1/Jump Start/0_Dark_Oracle_Jump Start_005.png'
  ],
  JUMPING_LOOP_ANIMATION: [
    './img/Character/lvl_1/Jump Loop/0_Dark_Oracle_Jump Loop_000.png',
    './img/Character/lvl_1/Jump Loop/0_Dark_Oracle_Jump Loop_001.png',
    './img/Character/lvl_1/Jump Loop/0_Dark_Oracle_Jump Loop_002.png',
    './img/Character/lvl_1/Jump Loop/0_Dark_Oracle_Jump Loop_003.png',
    './img/Character/lvl_1/Jump Loop/0_Dark_Oracle_Jump Loop_004.png',
    './img/Character/lvl_1/Jump Loop/0_Dark_Oracle_Jump Loop_005.png'
  ],
  FALLING_ANIMATION: [
    './img/Character/lvl_1/Falling Down/0_Dark_Oracle_Falling Down_000.png',
    './img/Character/lvl_1/Falling Down/0_Dark_Oracle_Falling Down_001.png',
    './img/Character/lvl_1/Falling Down/0_Dark_Oracle_Falling Down_002.png',
    './img/Character/lvl_1/Falling Down/0_Dark_Oracle_Falling Down_003.png',
    './img/Character/lvl_1/Falling Down/0_Dark_Oracle_Falling Down_004.png',
    './img/Character/lvl_1/Falling Down/0_Dark_Oracle_Falling Down_005.png'
  ],
  SLASHING_ANIMATION: [
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_000.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_001.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_002.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_003.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_004.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_005.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_006.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_007.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_008.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_009.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_010.png',
    './img/Character/lvl_1/Run Slashing/0_Dark_Oracle_Run Slashing_011.png'
  ]
};